name: Build & Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build Docker & Update Git for ArgoCD
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPO: ${{ secrets.ECR_REPO }}
      NAMESPACE: ${{ secrets.K8S_NAMESPACE }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image
        run: |
          docker build -t $ECR_REPO:$IMAGE_TAG .
          docker push $ECR_REPO:$IMAGE_TAG

      - name: Set up yq
        uses: chrisdickinson/setup-yq@v1.0.1

      - name: Update Helm Chart Values for ArgoCD
        run: |
          echo "Aggiornamento dinamico del tag immagine nel values.yaml..."
          # Modifica in modo sicuro la proprietà image.tag con il valore dell'ID del commit git
          yq -i ".image.tag = \"${{ env.IMAGE_TAG }}\"" flask-app-chart/values.yaml

      - name: Commit and Push changes back to Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add flask-app-chart/values.yaml
          
          # Esegue il commit solo se il file values.yaml è effettivamente cambiato
          git diff-index --quiet HEAD || git commit -m "chore: update image tag to $IMAGE_TAG [skip ci]"
          git push origin main
