    # 1. Configura la connessione verso il tuo cluster EC2 (Kubeadm)
    - name: Set up Kubeconfig for Kubeadm EC2
      run: |
        mkdir -p ~/.kube
        kubectl config set-cluster kubeadm-cluster --server=https://98.92.7.200:6443 --insecure-skip-tls-verify=true
        kubectl config set-credentials github-actions-user --token=${{ secrets.KUBEADM_TOKEN }}
        kubectl config set-context kubeadm-context --cluster=kubeadm-cluster --user=github-actions-user
        kubectl config use-context kubeadm-context

    # 2. Crea il namespace e inietta le chiavi ECR in automatico nello stesso step
    - name: Prepare Cluster and Deploy with Helm
      run: |
        echo "Creazione automatica del namespace..."
        kubectl create namespace ${{ secrets.K8S_NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -
        
        echo "Recupero credenziali AWS ECR..."
        TOKEN=$(aws ecr get-login-password --region $AWS_REGION)
        
        echo "Creazione del Secret per scaricare l'immagine..."
        kubectl create secret docker-registry regcred \
          --docker-server=://amazonaws.com \
          --docker-username=AWS \
          --docker-password=$TOKEN \
          --namespace ${{ secrets.K8S_NAMESPACE }} \
          --dry-run=client -o yaml | kubectl apply -f -
          
        echo "Avvio del deploy con Helm..."
        helm upgrade --install flask-app ./flask-app-chart \
          --namespace ${{ secrets.K8S_NAMESPACE }} \
          --set image.repository=$ECR_REPO \
          --set image.tag=$IMAGE_TAG \
          --set service.type=NodePort \
          --set imagePullSecrets.name=regcred
